language: cpp
compiler: gcc
git:
  depth: 0
before_install:
#  - sudo pip install cpplint rosdep
  - sudo pip install rosdep
  - sudo rosdep init && rosdep update 
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
install:
  - rosdep install --from-paths .. --ignore-src --rosdistro indigo
  - source /opt/ros/indigo/setup.bash
  - mkdir -p ~/catkin_ws/src && pushd ~/catkin_ws
  - catkin_init_workspace src
  - ln -s `eval echo $(dirs +1)` src/
script:
#  - catkin_make all kinect_aux_cpplint
   - catkin_make all
